### ISSUE TITLE
Explore converting to RHEL

### ISSUE THREAD

**Issue by andykrohg** [RedHatGov/workshop-terminal#1]
Images are currently built from CentOS S2I sources for convenience
workshop-terminal/terminal/Dockerfile

`FROM centos/s2i-base-centos7:latest`

This results in a number of problems, such as security scanners picking up bugs that haven't been fixed in CentOS but were in RHEL, as well as a slow release cadence to incorporate fixes for CentOS images compared to RHEL

We should explore how much work would need to be done to convert this image to a RHEL base, and if this has any impact on the downstream images:
https://github.com/redhatgov/workshop-dashboard
https://github.com/jharmison-redhat/openshift-devsecops-labguides

**Comment by jharmison-redhat** [comment]
Fixed in #2
